import Link from "next/link";
import Layout from "../components/Layout";
import { Inter } from "next/font/google";

import Image from "next/image";

import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const IndexPage = () => (
  <Layout title="Home | Next.js + TypeScript Example">
    <main className={`${styles.main} space-y-[5rem]`}>
      <h1 className={`${inter.className} text-5xl font-bold`}>
        <div className="flex place-items-center">
          <Link href="/about">Lloyd Lobo</Link>
          <span className={styles.thirteen}>👋</span>
        </div>
      </h1>

      <section>
        <div className="grid place-items-center space-y-8">
          <p className="text-start w-2/3">
            Hey, I'm Lloyd. Full-Time software developer. Focuses on Rust,
            Python & JavaScript/TypeScript. Makes apps, CLI tools, Discord bots,
            and novel websites. Likes dogs and cats.
          </p>
          <div className="flex place-items-center">
            <div>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
            <picture>
              <source
                srcSet="https://github-readme-stats.vercel.app/api?username=lloydlobo&show_icons=false&theme=dark&bg_color=00000000&hide_border=true&hide_title=true"
                media="(prefers-color-scheme: dark)"
              />
              <source
                srcSet="https://github-readme-stats.vercel.app/api?username=lloydlobo&show_icons=false&hide_border=true&hide_title=true"
                media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
              />
              <img src="https://github-readme-stats.vercel.app/api?username=lloydlobo&show_icons=false&hide_border=true&hide_title=true" />
            </picture>
          </div>
        </div>
      </section>
    </main>
  </Layout>
);

// https://github.com/anuraghazra/github-readme-stats
export default IndexPage;

/*
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
 */
